#!/bin/sh

DOTFILESDIR=$HOME/dotfiles
MD5SUM=`which md5sum`
if test -z "$MD5SUM" || ! test -x "$MD5SUM"; then
    MD5SUM=`which md5`
fi

if test ! -d $DOTFILESDIR; then
    echo "$DOTFILESDIR does not exist!  exiting"
    exit 1
fi

if test -z "$MD5SUM" || ! test -x "$MD5SUM"; then
    echo "Cannot find md5sum program"
    exit 1
fi

# --- Desktop environment detection ---
# Paths below are relative to the dotfiles root.
# Add paths here when you add DE-specific configs to the repo.
XFCE_ONLY="config/xfce4 config/redshift.conf Xclients Xclients-default xsession"
KDE_ONLY="config/kwinrc config/kglobalshortcutsrc config/kdeglobals config/dolphinrc"

detect_de() {
    de=`echo "${XDG_CURRENT_DESKTOP:-}" | tr '[:upper:]' '[:lower:]'`
    case "$de" in
        *kde*)   echo "kde"   ;;
        *xfce*)  echo "xfce"  ;;
        *gnome*) echo "gnome" ;;
        *)       echo "unknown" ;;
    esac
}

# Parse optional --de=<name> override (useful during initial setup before login)
# Use --force to overwrite files that differ from the repo version
DE_OVERRIDE=""
FORCE=0
for arg in "$@"; do
    case "$arg" in
        --de=*)  DE_OVERRIDE="${arg#--de=}" ;;
        --force) FORCE=1 ;;
    esac
done

if test -n "$DE_OVERRIDE"; then
    DE="$DE_OVERRIDE"
    echo "Desktop environment: $DE (forced)"
else
    DE=`detect_de`
    echo "Desktop environment: $DE (detected)"
fi

case "$DE" in
    kde)  SKIP_LIST="$XFCE_ONLY" ;;
    xfce) SKIP_LIST="$KDE_ONLY"  ;;
    all)  SKIP_LIST=""            ;;
    *)    SKIP_LIST=""            ;;
esac

should_skip() {
    # $1 = path relative to dotfiles root
    for skip in $SKIP_LIST; do
        case "$1" in
            "$skip"|"$skip/"*) return 0 ;;
        esac
    done
    return 1
}

# --- Linking ---
# linkdir <srcdir> <dstdir> <relbase>
#   relbase: path of srcdir relative to DOTFILESDIR, used for skip checks
linkdir () {
    for file in $1/*; do
        file=`basename $file`
        if test "$file" = "CVS" || test "$file" = "`basename $0`" || test "$file" = "README" || test "`echo $file | sed 's/^.*\(.\)/\1/'`" = "~"; then
            continue
        fi

        relpath="${3:+$3/}$file"
        if should_skip "$relpath"; then
            continue
        fi

        if test -d  "$1/$file"; then
            if test ! -d "$2/$DOT$file"; then
                mkdir $2/$DOT$file
            fi
            local OLDDOT=$DOT
            local DOT=
            linkdir $1/$file $2/$OLDDOT$file "$relpath"
            DOT=$OLDDOT
            continue
        elif test ! -f "$1/$file"; then
            continue
        fi
        if test -f $2/$DOT$file; then
            C_MD5SUM=`$MD5SUM < $2/$DOT$file | awk '{print $1}'`
            N_MD5SUM=`$MD5SUM < $1/$file | awk '{print $1}'`
            if test "$C_MD5SUM" = "$N_MD5SUM"; then
                rm -f $2/$DOT$file
            else
                if test "$FORCE" = "1"; then
                    echo "$2/$DOT$file differs from repo, overwriting"
                    rm -f $2/$DOT$file
                else
                    echo "$2/$DOT$file different from $1/$file, not known ok, and not symlink: skipping"
                    continue
                fi
            fi
        fi
        ln -s $1/$file $2/$DOT$file
    done
}

DOT=.
linkdir $DOTFILESDIR $HOME ""
