#! /bin/sh

if [ -f $HOME/.xsession-errors ]; then
    exec > $HOME/.xsession-errors 2>&1
    set -x
fi

if [ -f $HOME/.Xdefaults ]; then
    xrdb -merge $HOME/.Xdefaults
fi

# Debugging
echo `date`
source $HOME/.environment

xset +dpms
xset -b
xset dpms 0 0 120
xset r rate 250 50

if type metacity; then
    exec gnome-session
fi

if type fluxbox; then
    exec fluxbox
fi

# Absolute fallback
exec $XTERM
exec xterm
